---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Design and code improvements to a 2D version of Minecraft.
original_url: https://codeclubprojects.org/en-GB/python/codecraft
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introduction
- title: Playing the game
- title: 'Challenge: Build your world'
- title: Customising your game
- title: 'Challenge: Change your world size'
- title: Creating a new wood resource
- title: 'Challenge: Creating sand'
- title: Crafting planks from wood
- title: 'Challenge: Crafting glass from sand'
- title: 'Challenge: Create more resources'

