---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: コードクラフト
description: Design and code improvements to a 2D version of Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: はじめに
  - 
    title: ゲームをする
  - 
    title: 'チャレンジ：ワールドを構築'
  - 
    title: ゲームをカスタマイズする
  - 
    title: 'チャレンジ：ワールドのサイズを変更'
  - 
    title: 新しい木のリソースを作り出す
  - 
    title: 'チャレンジ：砂を作り出す'
  - 
    title: 木から板を作る
  - 
    title: 'チャレンジ：砂からガラスを作る'
  - 
    title: 'チャレンジ：さらにリソースを作り出す'
