---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Konzipiere und schreibe Code-Verbesserungen für eine 2D Version von Minecraft.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Das Spiel spielen
  - 
    title: 'Herausforderung: Bau dir deine Welt'
  - 
    title: Du kannst dein Spiel persönlicher gestalten
  - 
    title: 'Herausforderung: Ändere die Größe der Welt'
  - 
    title: Schaffe eine neue Ressource - Holz
  - 
    title: 'Herausforderung: Sand schaffen'
  - 
    title: Bretter aus Holz herstellen
  - 
    title: 'Herausforderung: Glas aus Sand herstellen'
  - 
    title: 'Herausforderung: Weitere Ressourcen herstellen'
