---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: En este proyecto diseñarás y codificarás mejoras en una versión en 2D de Minecraft.
version: 3.1.0
last_tested: 22-11-2018
steps:
  - 
    title: Introducción
  - 
    title: Jugando
  - 
    title: 'Desafío: Construye tu mundo'
  - 
    title: Personaliza tu juego
  - 
    title: 'Desafío: Cambiar el tamaño de tu mundo'
  - 
    title: Crea un nuevo recurso de madera
  - 
    title: 'Desafío: Crear arena'
  - 
    title: Elabora tablas de madera
  - 
    title: 'Desafío: Crear vidrio a partir de arena'
  - 
    title: 'Desafío: Crear más recursos'
