---
hero_image: images/banner.png
duration: 2
listed: true
copyedit: false
title: صناعة الأكواد
description: صمِّم تحسينات لنسخة ثنائية الأبعاد من لعبة ماين كرافت واكتب تعليماتها البرمجية.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - title: المقدمة
  - title: لعب اللعبة
  - title: 'التحدي: صمِّم عالمك'
  - title: تخصيص اللعبة
  - title: 'التحدي: غيِّر حجم عالمك'
  - title: إنشاء مورد خشب جديد
  - title: 'التحدي: أنشئ مورد الرمل'
  - title: صناعة ألواح خشبية من مورد الخشب
  - title: 'التحدي: اصنع الزجاج من الرمل'
  - title: 'التحدي: أنشئ موارد أخرى'
