---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Miglioramenti al design e al codice di una versione 2D di Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introduzione
  - 
    title: Il gioco
  - 
    title: 'Sfida: Costruisci il tuo mondo'
  - 
    title: Personalizzazione del gioco
  - 
    title: 'Sfida: Cambia le dimensioni del tuo mondo'
  - 
    title: Creazione della nuova risorsa legno
  - 
    title: 'Sfida: Crea la sabbia'
  - 
    title: Fabbricare tavole di legno
  - 
    title: 'Sfida: Fabbricare il vetro con la sabbia'
  - 
    title: 'Sfida: Crea altre risorse'
